export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Tarea</title>
  <base href="https://Andoni98.github.io/lopez_azpeitia_andoni_DWEC05_TareaEvaluativa01/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">body[_ngcontent-ng-c2766323463]{font-family:Arial,sans-serif;display:flex;justify-content:center;align-items:center;height:100vh;background-color:#f4f4f4}.container[_ngcontent-ng-c2766323463]{background:#fff;padding:20px;border-radius:10px;box-shadow:0 0 10px #0000001a;width:300px;text-align:center}h2[_ngcontent-ng-c2766323463]{color:#333}input[_ngcontent-ng-c2766323463]{width:100%;padding:8px;margin:5px 0;border:1px solid #ccc;border-radius:5px}button[_ngcontent-ng-c2766323463]{background:#28a745;color:#fff;border:none;padding:10px;margin-top:10px;cursor:pointer;border-radius:5px;width:100%}button[_ngcontent-ng-c2766323463]:disabled{background:#ccc;cursor:not-allowed}.error[_ngcontent-ng-c2766323463]{color:red;font-size:12px;margin-top:5px}.valid[_ngcontent-ng-c2766323463]{color:green;font-size:16px;margin-top:5px}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="19.2.3" _nghost-ng-c2766323463 ngh="0" ng-server-context="ssg"><div _ngcontent-ng-c2766323463><h2 _ngcontent-ng-c2766323463>Configuración del Juego</h2><label _ngcontent-ng-c2766323463>Nombre:</label><input _ngcontent-ng-c2766323463 type="text" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c2766323463 class="error">El nombre no puede estar vacío</div><!----><!----><label _ngcontent-ng-c2766323463>Apellido:</label><input _ngcontent-ng-c2766323463 type="text" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c2766323463 class="error">El apellido no puede estar vacío</div><!----><!----><label _ngcontent-ng-c2766323463>Rango Máximo:</label><input _ngcontent-ng-c2766323463 type="number" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c2766323463 class="error">El número debe ser 4 o más</div><!----><!----><label _ngcontent-ng-c2766323463>Número de Intentos:</label><input _ngcontent-ng-c2766323463 type="number" min="1" value class="ng-untouched ng-pristine ng-valid" jsaction="input:;blur:;compositionstart:;compositionend:;"><div _ngcontent-ng-c2766323463 class="error">Debe ingresar un número de intentos mayor o igual a 1</div><!----><!----><button _ngcontent-ng-c2766323463 disabled jsaction="click:;">Recoger Datos</button></div><!----><!----></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-JSB4YZ2Q.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"0":"t0","1":"t9"},"c":{"0":[{"i":"t0","r":1,"t":{"6":"t1","7":"t2","11":"t3","12":"t4","16":"t5","17":"t6","21":"t7","22":"t8"},"c":{"6":[{"i":"t1","r":1}],"7":[],"11":[{"i":"t3","r":1}],"12":[],"16":[{"i":"t5","r":1}],"17":[],"21":[{"i":"t7","r":1}],"22":[]}}],"1":[]}}]}</script></body></html>`;